### ISSUE TITLE
Given a circle with N defined points and a point M outside the circle, find the closest point.

### ISSUE THREAD

**Issue by jaytiwari** [mission-peace/interview#10]
I went through the solution given by you. it seems the solution is to search the minimum number in the circular array. Could you please explain the relation of the question with the solution?

**Comment by mission-peace** [comment]
Well. So there are N points on circle and there is one point M outside circle. Also it does not say if points on circle are given in what order. So basically you have can have first increasing then decreasing order(because points go farther and farther from M and then start coming close to M since its a circle). Or first decreasing then increasing order.  So I did binary search to find closest point on the circle from M.

**Comment by aktayal** [comment]
Hi Tushar, 
First of all, Appreciation for such a great detail that you have shared you video, here on github. Its really helpful. keep it up.
Now, the Algo you have provided for above problem fails for following case.
{7,3,2,5,9,1,0};
Decre - Incre - Decre case... Algo return 2 but it should return 0.
