### ISSUE TITLE
Complexity Analysis 

### ISSUE THREAD

**Issue by gongzelong0718** [mission-peace/interview#173]
https://github.com/mission-peace/interview/blob/master/src/com/interview/string/RemoveConsecutiveDuplicate.java

Could ylu help analyze what is the time complexity and storage complexity?

**Comment by atriagrawal** [comment]
Time complexity is O(n) where n is the length of the string. You are going through each character in the string only once in the loop even though you have nested while loop.

Space complexity is O(n) where n is the length of the string. You are creating an array of characters, so that is the extra space.

**Comment by gongzelong0718** [comment]
@atriagrawal 
Really appreciate your detailed explanation. :)
